// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	admin "nFlow/flow/internal/handler/admin"
	"nFlow/flow/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserLogMd},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: admin.LoginHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin/api/v1"),
	)
}
