// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	admin "nFlow/flow/internal/handler/admin"
	"nFlow/flow/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: admin.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/nflow/admin/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserPermitMd},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/getUserInfo",
					Handler: admin.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getDeptList",
					Handler: admin.GetDeptListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/addDept",
					Handler: admin.AddDeptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/updateDept",
					Handler: admin.UpdateDeptHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getUserList",
					Handler: admin.GetUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getRoleList",
					Handler: admin.GetRoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/switchRoleStatus",
					Handler: admin.SwitchRoleStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/addRole",
					Handler: admin.AddRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getPermitList",
					Handler: admin.GetPermitListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/dragglePermit",
					Handler: admin.DragglePermitHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/getRolePermit",
					Handler: admin.GetRolePermitHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/nflow/admin/api/v1"),
	)
}
