// Code generated by goctl. DO NOT EDIT.
package types

type RequestLogin struct {
	Phone    string `json:"username"`
	Password string `json:"password"`
}

type ResponseLogin struct {
	Message string `json:"message"`
}
