// Code generated by goctl. DO NOT EDIT.
package types

type RequestLogin struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type ResponseLogin struct {
	Token string `json:"token"`
}

type ResponseGetUserInfoRoleItem struct {
	RoleName string `json:"roleName"`
	Value    string `json:"value"`
}

type ResponseGetUserInfo struct {
	Roles    []ResponseGetUserInfoRoleItem `json:"roles"`
	UserId   int64                         `json:"userId"`
	Username string                        `json:"username"`
	RealName string                        `json:"realName"`
	Avatar   string                        `json:"avatar"`
	Desc     string                        `json:"desc"`
}

type RequestGetDeptList struct {
	Name   string `form:"name,optional"`
	Status int64  `form:"status,optional"`
	Top    int64  `form:"top,optional"`
}

type ResponseGetDeptList struct {
	Id         string `json:"id"`
	DeptCode   string `json:"deptCode"`
	DeptName   string `json:"deptName"`
	DeptDesc   string `json:"deptDesc"`
	DeptOrder  int64  `json:"deptOrder"`
	DeptParent string `json:"deptParent"`
	Status     int64  `json:"status"`
	CUser      string `json:"cUser"`
	UUser      string `json:"uUser"`
	CTime      string `json:"cTime"`
	UTime      string `json:"uTime"`
}

type RequestAddDept struct {
	DeptName   string `json:"deptName"`
	DeptDesc   string `json:"deptDesc"`
	DeptOrder  int64  `json:"deptOrder"`
	DeptParent string `json:"deptParent"`
	Status     int64  `json:"status"`
}

type RequestUpdateDept struct {
	DeptCode   string `json:"deptCode"`
	DeptName   string `json:"deptName"`
	DeptDesc   string `json:"deptDesc"`
	DeptOrder  int64  `json:"deptOrder"`
	DeptParent string `json:"deptParent"`
	Status     int64  `json:"status"`
}

type RequestGetUserList struct {
	UserAccount string `form:"userAccount,optional"`
	UserName    string `form:"userName,optional"`
	Status      int64  `form:"status,optional"`
	Dept        string `form:"dept,optional"`
	Page        int64  `form:"page,optional"`
	PageSize    int64  `form:"pageSize,optional"`
}

type ResponseGetUserList struct {
	UserCode      string `json:"userCode"`
	UserName      string `json:"userName"`
	UserAccount   string `json:"userAccount"`
	UserMail      string `json:"userMail"`
	UserAvatar    string `json:"userAvatar"`
	UserRoles     string `json:"userRoles"`
	UserRoleCodes string `json:"userRoleCodes"`
	UserDept      string `json:"userDept"`
	Status        int64  `json:"status"`
	CTime         string `json:"cTime"`
	UTime         string `json:"uTime"`
}

type ResponseGetUserListRes struct {
	Items []ResponseGetUserList `json:"items"`
	Total int64                 `json:"total"`
}

type RequestGetRoleList struct {
	RoleName string `form:"roleName,optional"`
	Status   int64  `form:"status,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type ResponseGetRoleList struct {
	RoleCode  string `json:"roleCode"`
	RoleDesc  string `json:"roleDesc"`
	RoleName  string `json:"roleName"`
	Status    int64  `json:"status"`
	RoleOrder int64  `json:"roleOrder"`
	CTime     string `json:"cTime"`
	UTime     string `json:"uTime"`
	CUser     string `json:"cUser"`
	UUser     string `json:"uUser"`
}

type ResponseGetRoleListRes struct {
	Items []ResponseGetRoleList `json:"items"`
	Total int64                 `json:"total"`
}

type RequestSwitchStatus struct {
	Code   string `json:"code"`
	Status int64  `json:"status"`
}

type RequestAddRole struct {
	RoleName  string   `json:"roleName"`
	RoleDesc  string   `json:"roleDesc"`
	RoleOrder int64    `json:"roleOrder"`
	Status    int64    `json:"status"`
	Permit    []string `json:"permit"`
}

type ResponseGetPermitList struct {
	PermitCode   string `json:"permitCode"`
	PermitName   string `json:"permitName"`
	PermitDesc   string `json:"permitDesc"`
	PermitOrder  int64  `json:"permitOrder"`
	PermitMethod string `json:"permitMethod"`
	PermitType   int64  `json:"permitType"`
	PermitUrl    string `json:"permitUrl"`
	PermitParent string `json:"permitParent"`
}

type RequestDragglePermit struct {
	Code  string `json:"code"`
	PCode string `json:"pCode,optional"`
}

type RequestGetRolePermit struct {
	Code string `form:"code"`
}

type ResponseGetRolePermit struct {
	Code []string `json:"code"`
}

type RequestUpdateRole struct {
	RoleName  string   `json:"roleName"`
	RoleCode  string   `json:"roleCode"`
	RoleDesc  string   `json:"roleDesc"`
	RoleOrder int64    `json:"roleOrder"`
	Status    int64    `json:"status"`
	Permit    []string `json:"permit"`
}

type RequestCheckUserAccount struct {
	Account string `json:"account"`
}

type ResponseCheckUserAccount struct {
	Code int64 `json:"code"`
}

type RequestKeyWord struct {
	Category string `form:"category"`
	Word     string `form:"word,optional"`
}

type ResponseKeyWord struct {
	Resp string `json:"resp"`
}

type RequestAddAccount struct {
	UserAccount string   `json:"userAccount"`
	UserName    string   `json:"userName"`
	Password    string   `json:"password"`
	Status      int64    `json:"status"`
	UserRoles   []string `json:"userRoles"`
	UserDept    string   `json:"userDept"`
	UserMail    string   `json:"userMail"`
}

type RequestUpdateAccount struct {
	UserCode    string   `json:"userCode"`
	UserAccount string   `json:"userAccount"`
	UserName    string   `json:"userName"`
	Status      int64    `json:"status"`
	UserRoles   []string `json:"userRoles"`
	UserDept    string   `json:"userDept"`
	UserMail    string   `json:"userMail"`
}
